### ISSUE TITLE
Invalid node type "all"

### ISSUE THREAD

**Issue by glyh** [moonbit-community/moonbit.nvim#17]
I recently updated neovim and I got this whenever I'm editing a moonbit file:

```
Error in decoration provider treesitter/highlighter.win:                                                                
Error executing lua: /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:252: Query error at 118:28. Invalid node type 
"all":                                                                                                                  
  "pub" "priv" "readonly" "all" "open" 
```

I assume this has something to do with treesitter's breaking changes?

**Comment by tonyfettes** [comment]
I guess you need to upgrade the treesitter to the latest version?

Technically things breaks on the query side, not on the TS side, but that's not important.

**Comment by tonyfettes** [comment]
This change does break many people's configuration. I'm thinking providing an automatic updating mechanism in this plugin so that the query is in-sync with the TS version.

@rami3l has a temporary solution to this by using a build hook in the lazy package manager.

**Comment by glyh** [comment]
Everything is up to date when I test this at least. and this occurs fairly recently.

tree-sitter CLI: 
```
 tree-sitter 0.24.3 (bdfe32402e85673bbc693216f0a6ef72c98bb665)
```

neovim: 
```
NVIM v0.10.2
Build type: RelWithDebInfo
LuaJIT 2.1.1731601260
```

nvim-treesitter: 

```
70d44da
```

**Comment by tonyfettes** [comment]
Try `:TSUpdate moonbit`?

**Comment by glyh** [comment]
ts doesn't seem to be finding the plugin. As the plugin is not loaded (I set it to load on moonbit file type).

![image](https://github.com/user-attachments/assets/993a776b-c62c-4c54-ba8f-31207a3abf2b)


But whenever I open a moonbit file, I'm stuck with infinite errors that even Ctrl+C won't do anything.

I do have a parser installed before when I was using this plugin.

EDIT: 

looks like setting `lazy = false` to the plugin temporarily and do TSUpdate fix this issue.

But I think it's better just expose the TS interface to end user.

**Comment by glyh** [comment]
Thanks for the info. Since this is just a out-of-date dependency issue, I'm closing it.
